name: Build and Package

on:
  push:
  fork:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, win, mac]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run build and package
      run: npx pkg app.js --output dist/app-${{ matrix.os }}

    - name: Generate badge links
      run: |
        echo "[![Download Latest ${{ matrix.os }}](https://img.shields.io/badge/Download-${{ matrix.os }}-brightgreen)](./dist/app-${{ matrix.os }})" >> README.md

    - name: Commit and push changes
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add README.md dist/app-${{ matrix.os }}
        git commit -m "Build and package for ${{ matrix.os }}"
        git push
