name: Build and Package

on:
  push:
  fork:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run build and package for Linux
        run: npx pkg app.js --output dist/app-linux

  build-win:
    runs-on: windows-latest
    needs: build-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run build and package for Windows
        run: npx pkg app.js --output dist/app-win

  build-mac:
    runs-on: macos-latest
    needs: build-win

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run build and package for macOS
        run: npx pkg app.js --output dist/app-mac

  push:
    runs-on: ubuntu-latest
    needs: [build-linux, build-win, build-mac]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove old badge lines
        run: sed -i '/\[!\[Download Latest/ {/^\s*$/!d}' README.md

      - name: Generate badge links and push changes
        run: |
          echo "[![Download Latest Linux](https://img.shields.io/badge/Download-Linux-brightgreen)](./dist/app-linux)" >> README.md
          echo "[![Download Latest Windows](https://img.shields.io/badge/Download-Windows-brightgreen)](./dist/app-win)" >> README.md
          echo "[![Download Latest macOS](https://img.shields.io/badge/Download-macOS-brightgreen)](./dist/app-mac)" >> README.md

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add README.md dist/
          git commit -m "Update badge links and artifacts"
          git push
